# Setup
title: "菜菜博士"
tagline: "博士在网络的家"
name: "菜菜博士"
url: http://microcai.org
description: "博士在网络的家"

permalink: date
#permalink: /:year-:month/:title/
paginate: 10

domain: microcai.org
title: 菜菜博士 - 博士在网络的家
author: microcai
email: microcaicai@gmail.com

github:
   username: microcai

disqus:
   id: drcai

# Parser
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables" ]

# Code highlight
highlighter: rouge

gems: [jekyll-paginate]
